import react from "react";
import { navLinks } from "../data";
import Link from "next/link";
import Image from "next/image";
import styles from "./header.module.css"
import Head from "next/head";

export default function Header() {
    const [hamburgerOpen, setHamburgerOpen] = react.useState(false)

    const toggleHamburger = (() => {
        setHamburgerOpen(!hamburgerOpen)
    })

    return (
        <>
        <Head>
            <title>Space</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1.0" />
            <link rel="icon" href="/favicon-32x32.png" />
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        </Head>
        <header className={styles.header}>
            <div className={styles.logo}>
                <Image
                    src='/images/logo.svg'
                    height={50}
                    width={50}
                    alt="logo"
                />
            </div>
            <div className={styles.line}><hr /></div>
            <nav className={styles.navBar}> 
                {navLinks.map((link) => {
                    return (
                        <>   
                        <ul className={styles.menuList}>  
                            <Link href={link.path} passHref>
                                <li key={link.num} className={styles.list}><span className={styles.menuNum}>{link.num}</span>{link.name}</li>
                            </Link>
                        </ul> 
                        </>
                    )
                })}    
            </nav>
            <nav className={styles.navMobile} style={hamburgerOpen ? {display: 'inline'} : {display: 'none'}}> 
                {navLinks.map((link) => {
                    return (
                        <>   
                        <ul className={styles.menuList}>  
                            <Link href={link.path} passHref>
                                <li key={link.num} className={styles.list}><span className={styles.menuNum}>{link.num}</span>{link.name}</li>
                            </Link>
                        </ul> 
                        </>
                    )
                })}    
            </nav> 
            <div className={styles.hamburger} onClick={toggleHamburger}>
                <div className={styles.burger} />
                <div className={styles.burger} />
                <div className={styles.burger} />
            </div>
        </header>
        </>
    )
}